[app]
    name = "go-web-template"

[server]
    name = "go-web-template"
    address = "127.0.0.1:8080"
    debug = true

[log]
    console = true
    level = "DEBUG"
    path = "./"
    file_name = "server.log"
    max_size = 100
    max_backups = 30
    max_age = 15
