[app]
    name = "go-web-template"

[server]
    name = "go-web-template"
    address = "0.0.0.0:80"
    debug = true

[log]
    console = true
    level = "DEBUG"
    path = "./"
    file_name = "server.log"
    max_size = 100
    max_backups = 30
    max_age = 15

[otel.trace]
    endpoint = "127.0.0.1:4318"
    insecure = true
    kind = "server"
    scope_name = "BJ"
    service_namespace = "go-web-template"
    service_name = "admin"
    service_version = "v1.0.0"
